### ISSUE TITLE
Build dependencies as an option

### ISSUE THREAD

**Issue by SnathanP** [bsord/helm-push#21]
Hello there,

I started using this action for pipelines (thanks for your work) and I faced an issue with charts having requirements/dependencies:
``` sh
Error: found in Chart.yaml, but missing in charts/ directory: redis
```
Looking at entrypoint.sh, this is coherent because the job is packaging the chart, but not checking for dependencies.
I suggest :
- we add the dependency fetching as an option and in the entrypoint.sh
- or we directly add the `-u` flag in [`helm package`](https://github.com/bsord/helm-push/blob/4934ee9536b0794357deec4befcd022138f61c14/entrypoint.sh#L74) commands

**Comment by bsord** [comment]
I really like this idea. I'm open to PRs if you want to contribute. Otherwise I will try to get it added in the next week or so.

**Comment by SnathanP** [comment]
Hello there, came back from holidays, here is a proposal
